port: 4001
log_level: "debug"
expired_in: 7200
db:
  max_con: 20
  max_idle_con: 5
  driver_name: "mysql"
  data_sources:
    - "root:root@tcp(127.0.0.1:3306)/cloud"
redis:
  host: "127.0.0.1:6379" # suhc-elevtest-01:7379
  pwd: "123456"
cos:
  cos_key: "TECENTCLOUDSECRETKEY"
  cos_id : "TECENTCLOUDSECRETID"
  cos_addr : "https://my-storage-1306331535.cos.ap-nanjing.myqcloud.com"